### ISSUE TITLE
 ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed

### ISSUE THREAD

**Issue by Modhi** [secure-software-engineering/soot-infoflow-android#107]
Hello,
I got the following error after calling runInfoflow() to analyze the app found on https://play.google.com/store/apps/details?id=com.trustgo.mobile.security

Could not find assignment to local $i0 in method <android.support.v4.app.i: android.view.View a(int)>
Could not find assignment to local $i0 in method <android.support.v4.app.i: android.view.View a(int)>
Could not find assignment to local $i0 in method <android.support.v4.app.i: android.view.View a(int)>
Could not find assignment to local $i0 in method <android.support.v4.app.i: android.view.View a(int)>
Could not find assignment to local $i0 in method <android.support.v4.app.i: android.view.View a(int)>
Could not find assignment to local $i0 in method <android.support.v4.app.i: android.view.View a(int)>
Could not find assignment to local $i0 in method <android.support.v4.app.i: android.view.View a(int)>
Could not find assignment to local $i0 in method <android.support.v4.app.i: android.view.View a(int)>
Could not find assignment to local $i0 in method <android.support.v4.app.i: android.view.View a(int)>
[Thread-25] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
[Thread-24] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
        at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargetsInternal(InfoflowProblem.java:810)
        at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargets(InfoflowProblem.java:734)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:94)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:38)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:322)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$000(IFDSSolver.java:62)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:639)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Could not find assignment to local $i0 in method <android.support.v4.app.i: android.view.View a(int)>
Could not find assignment to local $i0 in method <android.support.v4.app.i: android.view.View a(int)>
java.lang.NullPointerException
        at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargetsInternal(InfoflowProblem.java:810)
        at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargets(InfoflowProblem.java:734)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:94)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:38)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:322)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$000(IFDSSolver.java:62)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:639)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-25" Exception in thread "Thread-24" java.lang.NullPointerException
        at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargetsInternal(InfoflowProblem.java:810)
        at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargets(InfoflowProblem.java:734)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:94)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:38)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:322)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$000(IFDSSolver.java:62)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:639)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargetsInternal(InfoflowProblem.java:810)
        at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargets(InfoflowProblem.java:734)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:94)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:38)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:322)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$000(IFDSSolver.java:62)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:639)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by Modhi** [comment]
This issue happens frequently!
For some apps changing flowdroid configurations helps avoiding the issue, e.g., disabling implicit flows. However, for the apps-- facebook,instagram,autolist, skype,snapchat,twitter-- it is still occurring!

**Comment by StevenArzt** [comment]
Please update soot-infoflow and see if that helps. A new nightly build will be available tomorrow.

**Comment by Modhi** [comment]
Thank you.
