### ISSUE TITLE
java.lang.ClassCastException: soot.RefType cannot be cast to soot.ArrayType

### ISSUE THREAD

**Issue by vitaliiavdiienko** [secure-software-engineering/soot-infoflow-android#11]
Hi all,

i have faced with the following problem during analysis of the application.
I am using the latest version of soot-infoflow-android and all related projects.

Below is a stack-trace:

java.lang.ClassCastException: soot.RefType cannot be cast to soot.ArrayType
        at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.computeAliases(BackwardsInfoflowProblem.java:241)
        at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.access$4(BackwardsInfoflowProblem.java:93)
        at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1$1.computeTargets(BackwardsInfoflowProblem.java:302)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:76)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:1)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:410)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$1(IFDSSolver.java:403)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:539)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Exception in thread "pool-2-thread-7" java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:996)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
        at heros.solver.CountLatch.awaitZero(CountLatch.java:75)
        at heros.solver.CountingThreadPoolExecutor.awaitCompletion(CountingThreadPoolExecutor.java:67)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:194)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:175)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:151)
        at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:412)
        at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:265)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:478)
        at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:475)
        at soot.jimple.infoflow.android.TestApps.Test.access$0(Test.java:430)
        at soot.jimple.infoflow.android.TestApps.Test$2.call(Test.java:330)
        at soot.jimple.infoflow.android.TestApps.Test$2.call(Test.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
java.lang.ClassCastException: soot.RefType cannot be cast to soot.ArrayType
        at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.computeAliases(BackwardsInfoflowProblem.java:241)
        at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.access$4(BackwardsInfoflowProblem.java:93)
        at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1$1.computeTargets(BackwardsInfoflowProblem.java:302)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:76)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:1)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:410)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$1(IFDSSolver.java:403)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:539)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Infoflow computation failed: java.lang.RuntimeException: There were exceptions during IDE analysis. Exiting.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: There were exceptions during IDE analysis. Exiting.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:202)
        at soot.jimple.infoflow.android.TestApps.Test.runAnalysisTimeout(Test.java:348)
        at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:216)
Caused by: java.lang.RuntimeException: There were exceptions during IDE analysis. Exiting.
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:200)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:175)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:151)
        at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:412)
        at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:265)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:478)
        at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:475)
        at soot.jimple.infoflow.android.TestApps.Test.access$0(Test.java:430)
        at soot.jimple.infoflow.android.TestApps.Test$2.call(Test.java:330)
        at soot.jimple.infoflow.android.TestApps.Test$2.call(Test.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassCastException: soot.RefType cannot be cast to soot.ArrayType
        at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.computeAliases(BackwardsInfoflowProblem.java:241)
        at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.access$4(BackwardsInfoflowProblem.java:93)
        at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1$1.computeTargets(BackwardsInfoflowProblem.java:302)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:76)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:1)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:410)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$1(IFDSSolver.java:403)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:539)
        ... 3 more

I am using --implicit and --nostatic option.

I will send you my app per email if it is needed.

Thank you in advance,
Vitalii

**Comment by StevenArzt** [comment]
Should be fixed now.
