### ISSUE TITLE
RuntimeException when creating callgraph

### ISSUE THREAD

**Issue by dfbravo** [secure-software-engineering/soot-infoflow-android#128]
Hello everyone,

I am trying to create a callgraph for an opera browser apk ([link to apkpure download](https://apkpure.com/opera-browser-fast-safe/com.opera.browser)) using the following code:

```java
        SetupApplication app = new SetupApplication
            (androidPlatformPath,
             appPath);

        app.calculateSourcesSinksEntrypoints(SourcesAndSinksTxtPath);
        soot.G.reset();

        List<String> excludeList = new LinkedList<String>();
        excludeList.add("java.*");
        excludeList.add("sun.misc.*");
        excludeList.add("android.*");
        excludeList.add("org.apache.*");
        excludeList.add("soot.*");
        excludeList.add("javax.servlet.*");
        Options.v().set_exclude(excludeList);   
        Options.v().set_no_bodies_for_excluded(true);

        Options.v().set_output_format(Options.output_format_none);
        Options.v().set_src_prec(Options.src_prec_apk);
        Options.v().set_process_dir(Collections.singletonList(appPath));
        Options.v().set_force_android_jar(androidPlatformPath);
        Options.v().set_whole_program(true);
        Options.v().set_allow_phantom_refs(true);
        Options.v().setPhaseOption("cg.spark", "on");

        Scene.v().loadNecessaryClasses();

        SootMethod entryPoint = app.getEntryPointCreator().createDummyMain();
        Options.v().set_main_class(entryPoint.getSignature());
        Scene.v().setEntryPoints(Collections.singletonList(entryPoint));
        PackManager.v().runPacks();

        CallGraph cg = Scene.v().getCallGraph();
```

I get the following error when the callgraph is being created:

```
Exception in thread "main" java.lang.RuntimeException: no active body present for method <android.support.v4.content.FileProvider: void <clinit>()>
	at soot.SootMethod.getActiveBody(SootMethod.java:299)
	at soot.toolkits.scalar.ConstantInitializerToTagTransformer.transformClass(ConstantInitializerToTagTransformer.java:75)
	at soot.PackManager.runPacksNormally(PackManager.java:476)
	at soot.PackManager.runPacks(PackManager.java:396)
	at Main.main(Main.java:104)
```
(full log: [opera_fast_safe.txt](https://github.com/secure-software-engineering/soot-infoflow-android/files/390834/opera_fast_safe.txt))

I tried including the Android Support Libraries since it probably contains the body of the method. I tried adding the jar file through the soot classpath:

```java
        Options.v().set_soot_classpath(androidSupportV4Path);
```

Now I am getting the following error:

```
Exception in thread "main" java.util.NoSuchElementException: HashChain.LinkIterator.next() reached end of chain without reaching specified tail unit
	at soot.util.HashChain$LinkIterator.next(HashChain.java:665)
	at soot.PatchingChain$PatchingIterator.next(PatchingChain.java:278)
	at soot.PatchingChain$PatchingIterator.next(PatchingChain.java:267)
	at soot.toolkits.graph.ExceptionalUnitGraph.buildExceptionDests(ExceptionalUnitGraph.java:344)
	at soot.toolkits.graph.ExceptionalUnitGraph.initialize(ExceptionalUnitGraph.java:272)
	at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:159)
	at soot.dexpler.TrapMinimizer.internalTransform(TrapMinimizer.java:60)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.BodyTransformer.transform(BodyTransformer.java:58)
	at soot.BodyTransformer.transform(BodyTransformer.java:63)
	at soot.dexpler.DexBody.jimplify(DexBody.java:679)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:150)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:326)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:531)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:420)
	at soot.jimple.spark.solver.OnFlyCallGraph.build(OnFlyCallGraph.java:55)
	at soot.jimple.spark.solver.PropWorklist.handleVarNode(PropWorklist.java:122)
	at soot.jimple.spark.solver.PropWorklist.propagate(PropWorklist.java:52)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:152)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:118)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:576)
	at soot.PackManager.runPacksNormally(PackManager.java:467)
	at soot.PackManager.runPacks(PackManager.java:396)
	at Main.main(Main.java:104)
```
(full log: [opera_fast_safe_with_support.txt](https://github.com/secure-software-engineering/soot-infoflow-android/files/390840/opera_fast_safe_with_support.txt))

I used the android-19 jar and the support-v4-19.0.0 jar file.I downloaded both from the SDK manager that came with Android Studio. I can provide the jar files on request.

Thanks.

@StevenArzt

**Comment by ruitaohou** [comment]
Hello, have you solved this problem?
