### ISSUE TITLE
java.lang.RuntimeException: Type mask not found for type javax.xml.stream.XMLInputFactory

### ISSUE THREAD

**Issue by neha-jashnani** [secure-software-engineering/soot-infoflow-android#13]
Hi all,

yet another bug in Soot during analysing of apps :(

[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Spark] Pointer Assignment Graph in 0.1 seconds.
[Spark] Type masks in 0.0 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
Exception in thread "main" java.lang.RuntimeException: Type mask not found for type javax.xml.stream.XMLInputFactory
	at soot.jimple.spark.internal.TypeManager.get(TypeManager.java:87)
	at soot.jimple.spark.sets.HybridPointsToSet.nativeAddAll(HybridPointsToSet.java:54)
	at soot.jimple.spark.sets.HybridPointsToSet.addAll(HybridPointsToSet.java:143)
	at soot.jimple.spark.sets.PointsToSetInternal.addAll(PointsToSetInternal.java:37)
	at soot.jimple.spark.sets.HybridPointsToSet.superAddAll(HybridPointsToSet.java:44)
	at soot.jimple.spark.sets.HybridPointsToSet.addAll(HybridPointsToSet.java:140)
	at soot.jimple.spark.sets.DoublePointsToSet.addAll(DoublePointsToSet.java:61)
	at soot.jimple.spark.solver.PropWorklist.handleVarNode(PropWorklist.java:221)
	at soot.jimple.spark.solver.PropWorklist.propagate(PropWorklist.java:53)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:152)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:116)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbackMethods(Unknown Source)
	at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(Unknown Source)
	at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(Unknown Source)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Unknown Source)
	at soot.jimple.infoflow.android.TestApps.Test.main(Unknown Source)

Thanks,

Neha Jashnani

**Comment by StevenArzt** [comment]
Since there has not been any activity in this thread for quite a while, no new reports have dropped in, and a major bug fix on the issue has happened in Soot, I close this report. If the problem still persist, feel free to open up a new report.
