### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by SelinaEd** [secure-software-engineering/soot-infoflow-android#130]
Hello,

I'm trying to use FlowDroid for the first time and keep having an error while doing (on ubuntu):
`java -cp soot-trunk.jar:soot-infoflow.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:slf4j-simple-1.7.5.jar:axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test "/home/sel/Documents/Malware/krvarma-android-samples-smsdemo.apk" /home/sel/Documents/workspace/Android/android-sdk-linux/platforms`

I keep getting:
Exception in thread "main" java.lang.NoSuchMethodError: soot.jimple.infoflow.collect.MyConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at soot.jimple.infoflow.problems.TaintPropagationResults.getResults(TaintPropagationResults.java:105)
	at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:421)
	at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:146)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:832)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:651)
	at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:240)

Can someone please tell me what i'm doing wrong?

**Comment by nanan1993** [comment]
i have the same problem!! how do you solve it? waiting waiting waiting...

**Comment by nanan1993** [comment]
OK...finally i find it, try to use jdk8 to run instead of 7. hope to help you friend...

**Comment by SelinaEd** [comment]
Thanks.. that just tried it and it worked!
