### ISSUE TITLE
Build sensitive API call graph

### ISSUE THREAD

**Issue by wdbhust** [secure-software-engineering/soot-infoflow-android#161]
I want to build a sensitive API call graph for Android app. The node in the graph is a sensitive API (e.g., getDeviceId()) and the edge indicates that a sensitive API f calls (directly or indirectly) another sensitive API g. Is it possible to build the graph through the FlowDroid interface? Thanks

**Comment by mbenz89** [comment]
I am not exactly sure what a document API is, but in general terms, you could use FlowDroid to generate a call graph for the specific Android app and afterwards delete all edges and nodes you are not interested in.
If you are just interested in a certain list of APIs, like sensitive APIs mined by SuSi, you could generate a method that calls all these APIs, generate a call graph for it and, afterwards, delete nodes and edges you are not interested in.

Hope that helps
Manuel

**Comment by wdbhust** [comment]
Hi Manuel,
Thanks for your reply.

**Comment by ankitku** [comment]
Hi, I am not able to generate call graph. 
My code looks like this : 

			Scene.v().loadNecessaryClasses();

			SootMethod entryPoint = app.getDummyMainMethod();
			Options.v().set_main_class(entryPoint.getSignature());
			Scene.v().setEntryPoints(Collections.singletonList(entryPoint));
			System.out.println(entryPoint.getActiveBody());

	line 76:	PackManager.v().runPacks();
			PackManager.v().getPack("cg").apply();

			CallGraph appCallGraph = Scene.v().getCallGraph();


I am getting this exception : 

[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at soot.util.LargeNumberedMap.put(LargeNumberedMap.java:44)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.addVirtualCallSite(OnFlyCallGraphBuilder.java:688)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.findReceivers(OnFlyCallGraphBuilder.java:716)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:703)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:238)
	at soot.jimple.spark.solver.OnFlyCallGraph.build(OnFlyCallGraph.java:74)
	at soot.jimple.spark.builder.ContextInsensitiveBuilder.build(ContextInsensitiveBuilder.java:86)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:84)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:118)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:564)
	at soot.PackManager.runPacksNormally(PackManager.java:455)
	at soot.PackManager.runPacks(PackManager.java:384)
	at soot.jimple.infoflow.android.TestApps.CFG.main(CFG.java:76)

**Comment by doo1234** [comment]
The warning `[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.` gives in my application as well. Probably I hope @mbenz89  can answer this. 

What is this warning ?
How can we avoid this ?

**Comment by ericbodden** [comment]
Hi. The warning `[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase` occurs almost always, as call-graph construction is almost never truly complete. There are almost always some native calls, for instance, that neither Soot nor FlowDroid fully model. In those cases, those calls are unsoundly ignored during call-graph construction. If you use the option `-p cg:verbose` then Soot should tell you which are the problematic calls. The ArrayIndexOutOfBoundsException is rather unexpected. This should not be happening.

**Comment by doo1234** [comment]
Thank you very much for your explanation. 
As I understood from the above explanation, the option `-p cg:verbose` just gives the problematic calls but not a solution to the incomplete call graph. `ArrayIndexOutOfBoundsException` not gives in my application and only the warning is populated. As you mentioned the warning is given in almost all call- graphs and the reason is still unclear to me. Can you please give an example which soot unable to construct the full call graph (for understanding purpose) ?

**Comment by ericbodden** [comment]
Assume you have a method call such as:

b = System.arrayCopy(a);

Here arrayCopy is a native method, and generally Soot cannot know what it does. Some such native methods Soot explicitly “knows” and models internally, but others it does not. If Soot encounters a call to a native method it does not “know” then you see the warning you mentioned.

Cheers
Eric

**Comment by doo1234** [comment]
It is clear. Thank you for the explanation.
