### ISSUE TITLE
java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException

### ISSUE THREAD

**Issue by AnshumanRohella** [secure-software-engineering/soot-infoflow-android#181]
I tried using FlowDroid on my apk-debug.apk and got the following exception.
Command:
`java -Xmx4g -cp soot-trunk.jar:soot-infoflow.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:slf4j-simple-1.7.5.jar:axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test apk-debug.apk /Users/anshumanrohella/Library/Android/sdk/platforms`

Exception:
`Exception in thread "main" java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.xmlpull.v1.XmlPullParserException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more`
I am using a mac and have the axml-2.0.jar and all the other jar files in my root folder.  I really don't wanna build everything from the source.

**Comment by chocologurt** [comment]
Hi, 

I had the same problem as well, but I managed to solve it. Be sure to check the namings of the jar files that you have downloaded. My error surfaced due to the naming of the JAR files.

**Comment by StevenArzt** [comment]
This in an old version of FlowDroid. Please migrate to https://github.com/secure-software-engineering/FlowDroid.
