### ISSUE TITLE
FlowDroid 2.0 Call Graph , APIs have changed ? And  java.lang.ArrayIndexOutOfBoundsException when get call graph

### ISSUE THREAD

**Issue by NJUchengshuo** [secure-software-engineering/soot-infoflow-android#189]
I have built the FlowDroid-2.0 . When I tried to get CG , I found the API `CalculateSourcesAndSinks` was wrong. Did it change to `runInfoflow` ? In other words, should I use `runInfoflow` instead of `CalculateSourcesAndSinks` now ? I only want to get the CallGraph . So I don't need to use  `CalculateSourcesAndSinks` or`runInfoflow` but just `SetupApplication.constructCallgraph()` , right?
Another question:
I want to get the CG of an Apk. My code is just like this:
        `SetupApplication app = new SetupApplication(jarPath, apk);`
        `try{            app.runInfoflow(sourcesAndSinks);
        }catch(Exception e){
            e.printStackTrace();
        }
        soot.G.reset();`

        Options.v().set_src_prec(Options.src_prec_apk);
        Options.v().set_process_dir(Collections.singletonList(apk));
        Options.v().set_force_android_jar(jarPath );
        Options.v().set_whole_program(true);
        Options.v().set_allow_phantom_refs(true);
        Options.v().set_output_format(Options.output_format_none);
        Options.v().setPhaseOption("cg.spark verbose:true", "on");
        Scene.v().loadNecessaryClasses();

        SootMethod entryPoint = app.getDummyMainMethod();
        Options.v().set_main_class(entryPoint.getSignature());
        Scene.v().setEntryPoints(Collections.singletonList(entryPoint));
        PackManager.v().runPacks();    //Here is Line 53!!!
        CallGraph cg = Scene.v().getCallGraph();`
I got the Exception:
 Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at soot.util.LargeNumberedMap.put(LargeNumberedMap.java:44)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.addVirtualCallSite(OnFlyCallGraphBuilder.java:707)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.findReceivers(OnFlyCallGraphBuilder.java:735)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:722)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:255)
	at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:104)
	at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:46)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:118)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:564)
	at soot.PackManager.runPacksNormally(PackManager.java:455)
	at soot.PackManager.runPacks(PackManager.java:384)
	at CGGenerator.main(CGGenerator.java:53)

So could someone help to solve it?

**Comment by NJUchengshuo** [comment]
@Steven Arzt @Alexandre-Bartel @jpstotz @hjjandy @nguyenLisa

**Comment by kbelkhir** [comment]
any solution ? i have the same problem
