### ISSUE TITLE
how to use constructCallgraph properly?

### ISSUE THREAD

**Issue by hanada31** [secure-software-engineering/soot-infoflow-android#191]
I want to only generate the call graph of an android app without source and sink. I have the following code：

public static void main(String[] args) {
		SetupApplication app = new SetupApplication(Constant.android_jar_path, "test/apk/aGrep.apk");
		app.setCallbackFile("AndroidCallbacks.txt");
		app.constructCallgraph();
		Scene.v().getCallGraph();
	}

But I got an exception,

Exception in thread "main" java.lang.NoSuchMethodError: soot.Scene.makeSootField(Ljava/lang/String;Lsoot/Type;)Lsoot/SootField;
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchThreadImplementation(LibraryClassPatcher.java:178)
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchLibraries(LibraryClassPatcher.java:47)
	at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1021)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1187)
	at soot.jimple.infoflow.android.SetupApplication.constructCallgraph(SetupApplication.java:1077)
	at main.Main.main(Main.java:32)

What's the problem?
how can I use constructCallgraph properly?

**Comment by hanada31** [comment]
I miss some jar files in https://github.com/secure-software-engineering/soot-infoflow-android/wiki
now it is ok!

**Comment by umang78** [comment]
I am using constructCallgraph() method and it is reducing the size of the APK. Please help to resolve this issue.

**Comment by bay0max** [comment]
how to set the output path for callgraph?

**Comment by StevenArzt** [comment]
@bay0max You are using an outdated version of FlowDroid. Please use https://github.com/secure-software-engineering/FlowDroid instead.

**Comment by umang78** [comment]
Good evening sir,
I am trying to get all the components of an application by processing
manifest, but it is giving for some apps and not giving for many
applications please tell the reason behind this.

**Comment by StevenArzt** [comment]
@umang78 You are using an outdated version of FlowDroid. Please use https://github.com/secure-software-engineering/FlowDroid instead.
