### ISSUE TITLE
Error when running FlowDroid 2.0

### ISSUE THREAD

**Issue by bkarthikUT** [secure-software-engineering/soot-infoflow-android#202]
Hi,
I downloaded all the jar files for 2.0, then added the EasyTaintWrapperSource.txt and SourcesAndSinks.txt from FlowDroid source files. The following is my command line:

java -Xmx4g -cp sootclasses-trunk-jar-with-dependencies.jar:soot-infoflow.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:slf4j-simple-1.7.5.jar:axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test "SimpleNotepad.apk" /Users/UserName/Library/Android/sdk/platforms

when I run the above command, I see the following error:
[main] INFO soot.jimple.infoflow.taintWrappers.EasyTaintWrapper - Loaded wrapper entries for 89 classes and 12 exclusions.
Running data flow analysis...
Exception in thread "main" java.lang.NoSuchMethodError: soot.Body.getUnits()Lsoot/PatchingChain;
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchHandlerPostBody(LibraryClassPatcher.java:386)
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchHandlerImplementation(LibraryClassPatcher.java:285)
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchLibraries(LibraryClassPatcher.java:44)
	at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1021)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1187)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1160)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:798)
	at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:249)

It would be great if you can please help.

Thanks!

**Comment by StevenArzt** [comment]
Can you please check whether the problem still occurs with the current version of FlowDroid (https://github.com/secure-software-engineering/FlowDroid)? The 2.0 version is pretty old by now.

**Comment by bkarthikUT** [comment]
The problem does not occur with the latest version of FlowDroid(2.6.1). Thanks for your response.
