### ISSUE TITLE
FLOWDROID ERROR - xception in thread "main" java.lang.NoSuchMethodError: soot.Body.getUnits()Lsoot/PatchingChain;

### ISSUE THREAD

**Issue by jpuentea** [secure-software-engineering/soot-infoflow-android#204]
I'm trying to use FlowDroid for the first time and keep having an error while doing (on windows):

`java -Xmx4g -cp sootclasses-trunk-jar-with-dependencies.jar;soot-infoflow.jar;soot-infoflow-android.jar;slf4j-api-1.7.5.jar;slf4j-simple-1.7.5.jar;axml-2.0.jar s
oot.jimple.infoflow.android.TestApps.Test "C:\Users\javie\AndroidStudioProjects\Project\malware\73ddc408b518826064878dfc0064c4cd4fe512c0.apk" `C:\Users\javie\AppData\Local\Android\Sdk\platforms`

Running data flow analysis...
Exception in thread "main" java.lang.NoSuchMethodError: soot.Body.getUnits()Lsoot/PatchingChain;
at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchHandlerPostBody(LibraryClassPatcher.java:386)
at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchHandlerImplementation(LibraryClassPatcher.java:285)
at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchLibraries(LibraryClassPatcher.java:44)
at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1021)
at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1187)
at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1160)
at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:798)
at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:249)

**Comment by pangeneral** [comment]
I have the same problem, does anyone know what's the reason?

**Comment by StevenArzt** [comment]
You are using an outdated version of FlowDroid. Please switch to https://github.com/secure-software-engineering/FlowDroid.
