### ISSUE TITLE
Object-insensitive analysis fails

### ISSUE THREAD

**Issue by mikhail247** [secure-software-engineering/soot-infoflow-android#62]
Here is a command line
<..>\Facebook.apk <...>\sdk\platforms --noimplicit --nocallbacks --pathalgo sourcesonly --aplength 0 --cgalgo CHA

Facebook.apk is the facebook app downloaded from  Google Play (can't attach it because the apk is too big).

And here is the crash log

[main] INFO soot.jimple.infoflow.Infoflow - Callgraph has 4719 edges
[main] INFO soot.jimple.infoflow.Infoflow - Looking for sources and sinks...
[main] INFO soot.jimple.infoflow.Infoflow - Source lookup done, found 19 sources and 179 sinks.
[Thread-4] ERROR heros.solver.IDESolver - Worker thread execution failed: null
java.lang.AssertionError
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.computeAliases(BackwardsInfoflowProblem.java:104)
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.access$4(BackwardsInfoflowProblem.java:99)
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1$1.computeTargets(BackwardsInfoflowProblem.java:344)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:83)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:1)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:639)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$1(IFDSSolver.java:628)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:813)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-4" java.lang.AssertionError
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.computeAliases(BackwardsInfoflowProblem.java:104)
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.access$4(BackwardsInfoflowProblem.java:99)
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1$1.computeTargets(BackwardsInfoflowProblem.java:344)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:83)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:1)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:639)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$1(IFDSSolver.java:628)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:813)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at heros.solver.CountLatch.awaitZero(CountLatch.java:75)
	at heros.solver.CountingThreadPoolExecutor.awaitCompletion(CountingThreadPoolExecutor.java:79)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:264)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:239)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:195)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.solve(InfoflowSolver.java:115)
	at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:610)
	at soot.jimple.infoflow.Infoflow.computeInfoflowPostfix(Infoflow.java:398)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:615)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:546)
	at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:220)
Exception in thread "main" java.lang.RuntimeException: There were exceptions during IFDS analysis. Exiting.
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:270)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:239)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:195)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.solve(InfoflowSolver.java:115)
	at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:610)
	at soot.jimple.infoflow.Infoflow.computeInfoflowPostfix(Infoflow.java:398)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:615)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:546)
	at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:220)
Caused by: java.lang.AssertionError
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.computeAliases(BackwardsInfoflowProblem.java:104)
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1.access$4(BackwardsInfoflowProblem.java:99)
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1$1.computeTargets(BackwardsInfoflowProblem.java:344)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:83)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:1)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:639)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$1(IFDSSolver.java:628)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:813)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by StevenArzt** [comment]
Should be fixed now.

However, note that an access path limit of 0 only makes sense if static field tracking is disabled. Since a static field has no base, nit allowing a single field would lead to an empty taint. I have added a check for that, so you should now get an exception with a proper text when you try such invalid options.
