### ISSUE TITLE
 run flowdroid error on Ubuntu

### ISSUE THREAD

**Issue by fan123199** [secure-software-engineering/soot-infoflow-android#71]
when I run "java -Xmx4g -cp soot-trunk.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:slf4j-simple-1.7.5.jar:axml-2.0.jar:soot-infoflow.jar soot.jimple.infoflow.android.TestApps.Test ~/apks/SendSMS.apk ~/didfail/platforms/" in Ubuntu , occur the error blew:

Exception in thread "main" java.lang.NoClassDefFoundError: soot/jimple/infoflow/taintWrappers/ITaintPropagationWrapper
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
	at java.lang.Class.getMethod0(Class.java:2856)
	at java.lang.Class.getMethod(Class.java:1668)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.taintWrappers.ITaintPropagationWrapper
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

I'd be really grateful if you could help me about the problem.

**Comment by StevenArzt** [comment]
Your classpath seems to be wrong. Put soot-infoflow before soot-infoflow-android, not after. You can find a working classpath in the Wiki: https://github.com/secure-software-engineering/soot-infoflow-android/wiki#running-flowdroid

**Comment by fan123199** [comment]
I find the solution, but I still confused the reason. I change '-cp' to '-classpath' ,And then the tool is able to run.
