### ISSUE TITLE
soot.ArrayType cannot be cast to soot.RefType

### ISSUE THREAD

**Issue by vitaliiavdiienko** [secure-software-engineering/soot-infoflow-android#73]
Hi Steven,
I am using the latest FlowDroid and have the following exception.
If you need and app I can send it to you by email.

[Thread-3] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: soot.ArrayType cannot be cast to soot.RefType
java.lang.ClassCastException: soot.ArrayType cannot be cast to soot.RefType
	at soot.jimple.infoflow.data.AccessPath.<init>(AccessPath.java:256)
	at soot.jimple.infoflow.data.AccessPath.copyWithNewValue(AccessPath.java:589)
	at soot.jimple.infoflow.data.AccessPath.copyWithNewValue(AccessPath.java:573)
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstraction(Abstraction.java:196)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.addTaintViaStmt(InfoflowProblem.java:386)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.access$5(InfoflowProblem.java:336)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.createNewTaintOnAssignment(InfoflowProblem.java:756)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargetsInternal(InfoflowProblem.java:535)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$NotifyingNormalFlowFunction.computeTargets(InfoflowProblem.java:293)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:85)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:1)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:459)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$1(IFDSSolver.java:452)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-3" java.lang.ClassCastException: soot.ArrayType cannot be cast to soot.RefType
	at soot.jimple.infoflow.data.AccessPath.<init>(AccessPath.java:256)
	at soot.jimple.infoflow.data.AccessPath.copyWithNewValue(AccessPath.java:589)
	at soot.jimple.infoflow.data.AccessPath.copyWithNewValue(AccessPath.java:573)
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstraction(Abstraction.java:196)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.addTaintViaStmt(InfoflowProblem.java:386)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.access$5(InfoflowProblem.java:336)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.createNewTaintOnAssignment(InfoflowProblem.java:756)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargetsInternal(InfoflowProblem.java:535)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$NotifyingNormalFlowFunction.computeTargets(InfoflowProblem.java:293)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:85)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:1)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:459)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$1(IFDSSolver.java:452)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" java.lang.RuntimeException: There were exceptions during IFDS analysis. Exiting.
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:219)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:188)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:164)
	at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:551)
	at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:322)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:726)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:544)
	at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:228)
Caused by: java.lang.ClassCastException: soot.ArrayType cannot be cast to soot.RefType
	at soot.jimple.infoflow.data.AccessPath.<init>(AccessPath.java:256)
	at soot.jimple.infoflow.data.AccessPath.copyWithNewValue(AccessPath.java:589)
	at soot.jimple.infoflow.data.AccessPath.copyWithNewValue(AccessPath.java:573)
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstraction(Abstraction.java:196)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.addTaintViaStmt(InfoflowProblem.java:386)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.access$5(InfoflowProblem.java:336)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.createNewTaintOnAssignment(InfoflowProblem.java:756)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargetsInternal(InfoflowProblem.java:535)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$NotifyingNormalFlowFunction.computeTargets(InfoflowProblem.java:293)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:85)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:1)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:459)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$1(IFDSSolver.java:452)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Thanks in advance.

Best Regards,
Vitalii

**Comment by StevenArzt** [comment]
Please send me the app via e-mail. Without the app, it's hard to tell what's going wrong here.

**Comment by StevenArzt** [comment]
Should be fixed now.

**Comment by ezamorab** [comment]
Hi, Steven. 

I have a similar problem with the analysis of an apk.  I'm using the latest version but when I run the analysis in a certain apk I get this error:

[main] ERROR soot.jimple.infoflow.android.SetupApplication - Could not calculate callback methods
java.lang.ClassCastException: soot.ArrayType cannot be cast to soot.RefType
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.resolveInvoke(OnFlyCallGraphBuilder.java:383)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.addBaseType(OnFlyCallGraphBuilder.java:284)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.addType(OnFlyCallGraphBuilder.java:615)
	at soot.jimple.spark.solver.OnFlyCallGraph$2.visit(OnFlyCallGraph.java:139)
	at soot.jimple.spark.sets.HybridPointsToSet.forall(HybridPointsToSet.java:112)
	at soot.jimple.spark.solver.OnFlyCallGraph.updatedNode(OnFlyCallGraph.java:136)
	at soot.jimple.spark.solver.PropWorklist.handleVarNode(PropWorklist.java:158)
	at soot.jimple.spark.solver.PropWorklist.propagate(PropWorklist.java:81)
	at soot.jimple.spark.SparkTransformer.propagatePAG(SparkTransformer.java:238)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:155)
	at soot.SceneTransformer.transform(SceneTransformer.java:36)
	at soot.Transform.apply(Transform.java:102)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:68)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:58)
	at soot.Pack.apply(Pack.java:117)
	at soot.jimple.infoflow.android.SetupApplication.constructCallgraphInternal(SetupApplication.java:564)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbackMethods(SetupApplication.java:682)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:476)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:446)
	at soot.jimple.infoflow.android.SetupApplication.processEntryPoint(SetupApplication.java:1393)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1359)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1306)
	at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:333)
	at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:231)


I can send the apk to you if you need it. 

Thanks in advanced.

**Comment by StevenArzt** [comment]
@ezamorab Please open a new issue for new problems. Furthermore, you are using an outdated version of FlowDroid. Please switch to https://github.com/secure-software-engineering/FlowDroid
