### ISSUE TITLE
flowdroid gives error

### ISSUE THREAD

**Issue by pranavpnair** [secure-software-engineering/soot-infoflow-android#75]
Hello,
I'm using flowdroid ( by building it from source files) to analyse apk files to find invalid UI access from threads in the code. But it gives me the following error for most apk files. Pls help.

(The apk in this link gives the following exception : https://f-droid.org/repository/browse/?fdid=info.lamatricexiste.network)

Exception in thread "main" java.lang.RuntimeException: Failed to apply jb to <android.preference.GenericInflater: java.lang.Object inflate(org.xmlpull.v1.XmlPullParser,android.preference.GenericInflater$Parent,boolean)>
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1804)
	at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:529)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:420)
	at soot.jimple.spark.solver.OnFlyCallGraph.build(OnFlyCallGraph.java:55)
	at soot.jimple.spark.solver.PropWorklist.handleVarNode(PropWorklist.java:122)
	at soot.jimple.spark.solver.PropWorklist.propagate(PropWorklist.java:52)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:152)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:116)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbackMethods(SetupApplication.java:467)
	at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(SetupApplication.java:378)
	at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(SetupApplication.java:344)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:507)
	at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:210)
	at com.ibm.research.androidstatic.CG2.driver(CG2.java:11)
	at com.ibm.research.androidstatic.CG2.main(CG2.java:25)
Caused by: java.lang.IllegalStateException: UnitThrowAnalysis StmtSwitch: type of throw argument is not a RefType!
	at soot.toolkits.exceptions.AbstractThrowAnalysis.mightThrowExplicitly(AbstractThrowAnalysis.java:65)
	at soot.toolkits.exceptions.UnitThrowAnalysis$UnitSwitch.caseThrowStmt(UnitThrowAnalysis.java:706)
	at soot.jimple.internal.JThrowStmt.apply(JThrowStmt.java:70)
	at soot.toolkits.exceptions.UnitThrowAnalysis.mightThrow(UnitThrowAnalysis.java:241)
	at soot.toolkits.graph.ExceptionalUnitGraph.buildExceptionDests(ExceptionalUnitGraph.java:351)
	at soot.toolkits.graph.ExceptionalUnitGraph.initialize(ExceptionalUnitGraph.java:274)
	at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:159)
	at soot.jimple.toolkits.scalar.CopyPropagator.internalTransform(CopyPropagator.java:135)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:105)
	at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:75)
	at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:89)
	at soot.Pack.apply(Pack.java:126)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1802)
	... 20 more

**Comment by StevenArzt** [comment]
I'm not sure what went wrong on your machine. For me, it works all fine. Are you using the newest version of soot, soot-infoflow, and soot-infoflow-android?

**Comment by ZhengqiaoLi** [comment]
I want to build flowdroid from source.
but,I don't know how to do it? Because there are some error.
Can you give me some advice  and configuration?
Pls help.

**Comment by StevenArzt** [comment]
Which error do you get? Can you be a bit more specific?

**Comment by garimamodi02** [comment]
I want to build flowdroid from source. I have imported all projects in eclipse but i am getting multiple errors. Can u please tell the steps on how to build from source code.

**Comment by StevenArzt** [comment]
You need to import the newest´versions of heros, jasmine, soot, soot-infoflow, and soot-infoflow-android into Eclipse. Make sure to use the develop branches, not the master ones as the latter are horribly outdated.

**Comment by garimamodi02** [comment]
Thanks for the reply sir.
I have imported the required projects in eclipse. The error comes for
heros, liking missing return type of function, ) or ; missing. I have used
the heros version present on github

P.s.: all are develop branches
