### ISSUE TITLE
Seems dead loop within IFDSSlover

### ISSUE THREAD

**Issue by Jiezhi** [secure-software-engineering/soot-infoflow-android#85]
Hi, I've analysed some apks using this project.While with a few of particular apks,  the program running seemly endless (almost a whole night).(_Win 7 with 32G memory & 48 core Genuine Intel CPU @ 2GHz_)

When I debug this program with the apk, I found that the method **propagate()** in IFDSSolver.java continuous propagate and propagate.

I tried to find some solutions and can't found anything due to the huge structure of the project.

So, any help?

**Comment by Jiezhi** [comment]
You can download the apk from [here](https://www.dropbox.com/s/y2gu0blfj0at3lo/com.ami_vapor_modbus_11.apk?dl=0).

**Comment by StevenArzt** [comment]
This method is the propagation method of the core IFDS solver. Whenever FlowDroid processes an edges, it goes through here. This means that the method itself is neither faulty, not creates an infinite loop. There's just lots to do and it all goes through here. Have you tried the performance optimization techniques from the Wiki?

**Comment by Jiezhi** [comment]
I've analysed the APK with the option mentioned in the Wiki as below:
```shell
java -Xmx30g -cp soot-trunk.jar;soot-infoflow.jar;soot-infoflow-android.jar;slf4j-api-1.7.5.jar;slf4j-simple-1.7.5.jar;axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test "C:\xxx.apk" C:\Users\win7\AppData\Local\Android\sdk\platforms --nostatic --aplength 1 --aliasflowins --nocallbacks --layoutmode none --noarraysize
```

An hour later I got the error message:
```java
...
[main] INFO soot.jimple.infoflow.Infoflow - Looking for sources and sinks...
[main] INFO soot.jimple.infoflow.Infoflow - Source lookup done, found 25 sources and 83 sinks.
[Thread-13] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstractionMutable(Abstraction.java:193)
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstraction(Abstraction.java:174)
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstraction(Abstraction.java:163)
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1$3.computeTargets(BackwardsInfoflowProblem.java:670)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeReturnFlowFunction(InfoflowSolver.java:75)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeReturnFlowFunction(InfoflowSolver.java:38)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:297)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$000(IFDSSolver.java:61)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:629)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-13" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstractionMutable(Abstraction.java:193)
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstraction(Abstraction.java:174)
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstraction(Abstraction.java:163)
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1$3.computeTargets(BackwardsInfoflowProblem.java:670)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeReturnFlowFunction(InfoflowSolver.java:75)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeReturnFlowFunction(InfoflowSolver.java:38)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:297)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$000(IFDSSolver.java:61)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:629)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.RuntimeException: There were exceptions during IFDS analysis. Exiting.
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:219)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:188)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:164)
	at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:332)
	at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:137)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:698)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:558)
	at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:217)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstractionMutable(Abstraction.java:193)
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstraction(Abstraction.java:174)
	at soot.jimple.infoflow.data.Abstraction.deriveNewAbstraction(Abstraction.java:163)
	at soot.jimple.infoflow.problems.BackwardsInfoflowProblem$1$3.computeTargets(BackwardsInfoflowProblem.java:670)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeReturnFlowFunction(InfoflowSolver.java:75)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeReturnFlowFunction(InfoflowSolver.java:38)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:297)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$000(IFDSSolver.java:61)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:629)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
Does this mean I can't analysis this APK under 32GB memory even though with the minimal option?

I wonder that this APK is just 2MB size, why analysis is so difficult? While I analysed some bigger size apk just within few minutes with the default option.

**Comment by Jiezhi** [comment]
Hi, @StevenArzt sorry to bother you again.

I've tried analysing the APK on AWS with 244GB memory, no result within an hour.

Meanwhile tried it on 441GB machine  at school a whole night with no result.

It seems no solution with the APK but to find a super machine?

**Comment by StevenArzt** [comment]
Which version of FlowDroid do you use? I just tested your APK and it works fine:

```
Maximum memory consumption: 2341.169744 MB
Analysis has run for 19.767033574 seconds
```

**Comment by Jiezhi** [comment]
I've tried both the nightly builds from wiki and the latest code. No one works fine with the APK.

**Comment by StevenArzt** [comment]
Did you update all required components, i.e. soot, soot-infoflow, and soot-infoflow-android? Are you sure that you are using the APK from the link above? Are you using the platform JAR files from the Android SDK or ones from somewhere else?

That's very strange now, because it works fine for me.

**Comment by Jiezhi** [comment]
Today I updated all android.jar via SDK manager, and exported runnable FlowDroid.jar using the latest code.

The results get improved: some APKs cannot be analysed before were analysed successfully.

Sadly it still not worked fine with the APK above..

I'll do some more research on this recently, and update here once I have new discovery!

**Comment by miguelvelezmj25** [comment]
Is there an update on this issue? I have a similar problem. The analysis runs for hours on a big machine, it runs out of memory, and the IFDS problem has millions of forward and backward edges solved.
