### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException for test app

### ISSUE THREAD

**Issue by prajitdas** [secure-software-engineering/soot-infoflow-android#88]
I am testing FlowDroid using the FlowDroid jar and the following command.
Prompt> java -Xmx512m -jar FlowDroid.jar goldenshorestechnologies.brightestflashlight.free.apk $ANDROID_HOME\platforms
I am getting the following error:

 [main] INFO soot.jimple.infoflow.taintWrappers.EasyTaintWrapper - Loaded wrapper entries for 49 classes and 4 exclusions.
[main] INFO soot.jimple.infoflow.android.SetupApplication - ARSC file parsing took 0.0192174 seconds
Exception in thread "main" java.lang.NumberFormatException: For input string: "MNC"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at java.lang.Integer.valueOf(Unknown Source)
    at java.lang.Integer.decode(Unknown Source)
    at soot.Scene.getMaxAPIAvailable(Scene.java:270)
    at soot.Scene.getAndroidJarPath(Scene.java:285)
    at soot.jimple.infoflow.android.SetupApplication.initializeSoot(Unknown Source)
    at soot.jimple.infoflow.android.SetupApplication.calculateCallbackMethods(Unknown Source)
    at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(Unknown Source)
    at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(Unknown Source)
    at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Unknown Source)
    at soot.jimple.infoflow.android.TestApps.Test.main(Unknown Source)

Could you please help me figure out what the issue is?

**Comment by StevenArzt** [comment]
Can you please double-check that you are using the newest version of Soot? This bug should have been fixed a while ago.
