### ISSUE TITLE
NullPointerException at soot.jimple.infoflow.problems.InfoflowProblem.java

### ISSUE THREAD

**Issue by Jiezhi** [secure-software-engineering/soot-infoflow-android#89]
These days I got some exceptions like below:
```java
...
[main] INFO soot.jimple.infoflow.Infoflow - Source lookup done, found 59 sources and 40 sinks.
[Thread-39] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargetsInternal(InfoflowProblem.java:504)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargets(InfoflowProblem.java:458)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallFlowFunction(InfoflowSolver.java:103)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallFlowFunction(InfoflowSolver.java:1)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:261)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$0(IFDSSolver.java:246)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:648)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: There were exceptions during IFDS analysis. Exiting.
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:220)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:189)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:165)
	at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:332)
	at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:137)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:709)
	at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:521)
	at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:212)
	... 5 more
Caused by: java.lang.NullPointerException
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargetsInternal(InfoflowProblem.java:504)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargets(InfoflowProblem.java:458)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallFlowFunction(InfoflowSolver.java:103)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallFlowFunction(InfoflowSolver.java:1)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:261)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$0(IFDSSolver.java:246)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:648)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-39" java.lang.NullPointerException
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargetsInternal(InfoflowProblem.java:504)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargets(InfoflowProblem.java:458)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallFlowFunction(InfoflowSolver.java:103)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallFlowFunction(InfoflowSolver.java:1)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:261)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$0(IFDSSolver.java:246)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:648)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```
I just put the APK [HERE](https://www.dropbox.com/s/3sh7i0j1qr01j1t/com.apexedapp.app.android_4.apk?dl=0).

Bug or not?

**Comment by StevenArzt** [comment]
Should be fixed now. Interestingly, the exception did not occur in every run, but only in most runs. With the fix, a wasn't able to reproduce it anymore, so let's hope it's actually gone for good.

**Comment by majestyhao** [comment]
Sorry to comment on the closed issue. But I met the same problem for the app: https://f-droid.org/repo/com.haringeymobile.ukweather_20.apk
