### ISSUE TITLE
RuntimeException: Type mask not found

### ISSUE THREAD

**Issue by titze** [secure-software-engineering/soot-infoflow-android#9]
Hi,
I try to run a dataflow analysis on an app [1] from the google market and encounter the following error: 

java.lang.RuntimeException: Type mask not found for type android.gesture.GestureOverlayView$OnGesturePerformedListener
	at soot.jimple.spark.internal.TypeManager.get(TypeManager.java:87)
	at soot.jimple.spark.sets.HybridPointsToSet.nativeAddAll(HybridPointsToSet.java:54)
	at soot.jimple.spark.sets.HybridPointsToSet.addAll(HybridPointsToSet.java:143)
	at soot.jimple.spark.sets.DoublePointsToSet.addAll(DoublePointsToSet.java:61)
	at soot.jimple.spark.solver.PropWorklist.handleVarNode(PropWorklist.java:152)
	at soot.jimple.spark.solver.PropWorklist.propagate(PropWorklist.java:53)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:152)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
	at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
	at soot.Pack.apply(Pack.java:114)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:539)
	at soot.PackManager.runPacksNormally(PackManager.java:443)
	at soot.PackManager.runPacks(PackManager.java:388)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbackMethods(SetupApplication.java:292)
	at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(SetupApplication.java:229)
	at soot.jimple.infoflow.android.SetupApplication.calculateSourcesSinksEntrypoints(SetupApplication.java:199)
	at de.fhg.aisec.permsec.analysis.detectors.InfoLeakDetector.check(InfoLeakDetector.java:86)
	at de.fhg.aisec.permsec.analysis.detectors.InfoLeakDetector$2.run(InfoLeakDetector.java:149)

I think I traced the error down to soot.FastHierarchy:

The analysis checks if the canStoreClass("j$a", "GestureOverlayView$OnGesturePerformedListener") which should result in true (figured from looking at the smali).

But this returns false since the intervals are not a subrange of each other.

If I remove the part in the Constructor of FastHierarchy, where the phantom classes are added to the classToInterval, it works seems to work.

Is this a bug, or am I doing something strange?

Can/should I upload the checked apk somewhere?

Best regards,
Dennis

[1] https://play.google.com/store/apps/details?id=com.idom.alphahdwall

**Comment by StevenArzt** [comment]
We have fixed quite a number of issues related to these "type mask not found" exceptions in Soot. The problem does not occur on my machine anymore at least.
