### ISSUE TITLE
ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed

### ISSUE THREAD

**Issue by majestyhao** [secure-software-engineering/soot-infoflow-android#95]
When I test FlowDroid on a weather app (can be downloaded through https://drive.google.com/file/d/0B0L3QOYpU0GWYmhfdWN5a1dCcms/view?usp=sharing), I get the following errors
 ```
[Thread-1] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.hash(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
	at soot.jimple.infoflow.data.AccessPath.getBaseForType(AccessPath.java:453)
	at soot.jimple.infoflow.aliasing.Aliasing.getReferencedAPBase(Aliasing.java:152)
	at soot.jimple.infoflow.aliasing.Aliasing.mayAlias(Aliasing.java:287)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.createNewTaintOnAssignment(InfoflowProblem.java:269)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.access$200(InfoflowProblem.java:92)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$1.computeTargetsInternal(InfoflowProblem.java:415)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$NotifyingNormalFlowFunction.computeTargets(InfoflowProblem.java:120)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:85)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:38)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:459)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$100(IFDSSolver.java:61)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.RuntimeException: There were exceptions during IFDS analysis. Exiting.
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:219)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:188)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:164)
	at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:332)
	at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:137)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:700)
	at playFlowDroid.Test.runAnalysis(Test.java:563)
	at playFlowDroid.Test.main(Test.java:217)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.hash(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
	at soot.jimple.infoflow.data.AccessPath.getBaseForType(AccessPath.java:453)
	at soot.jimple.infoflow.aliasing.Aliasing.getReferencedAPBase(Aliasing.java:152)
	at soot.jimple.infoflow.aliasing.Aliasing.mayAlias(Aliasing.java:287)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.createNewTaintOnAssignment(InfoflowProblem.java:269)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.access$200(InfoflowProblem.java:92)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$1.computeTargetsInternal(InfoflowProblem.java:415)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$NotifyingNormalFlowFunction.computeTargets(InfoflowProblem.java:120)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:85)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:38)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:459)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$100(IFDSSolver.java:61)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-1" java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.hash(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
	at soot.jimple.infoflow.data.AccessPath.getBaseForType(AccessPath.java:453)
	at soot.jimple.infoflow.aliasing.Aliasing.getReferencedAPBase(Aliasing.java:152)
	at soot.jimple.infoflow.aliasing.Aliasing.mayAlias(Aliasing.java:287)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.createNewTaintOnAssignment(InfoflowProblem.java:269)
	at soot.jimple.infoflow.problems.InfoflowProblem$1.access$200(InfoflowProblem.java:92)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$1.computeTargetsInternal(InfoflowProblem.java:415)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$NotifyingNormalFlowFunction.computeTargets(InfoflowProblem.java:120)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:85)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:38)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:459)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$100(IFDSSolver.java:61)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:622)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by majestyhao** [comment]
Any app attach ad sdk like https://github.com/mopub/mopub-android-sdk will crash.

**Comment by arvind4141** [comment]
@majestyhao Hello, did you manage to solve this issue? I'm currently getting this same problem now too.

**Comment by pgadient** [comment]
It was a hack for an old version of FlowDroid, not sure if that will work out-of-the-box on recent releases. Additionally, this could dismiss potential results, so be careful using this code snippet. 
Didn't spend any time on developing a real proper fix so far.

**Comment by arvind4141** [comment]
@pgadient By any chance do you still have that specific modified version of FlowDroid? Would be great if you I use that a starting point, rather than digging through old FlowDroid versions.

**Comment by pgadient** [comment]
Please use the latest release on the dev branch, if you not already do, and verify that the issue still remains. In case you encounter any missing dependencies after you cloned the git repos, please include the "fat-jar" from [here](https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/build/sootclasses-trunk-jar-with-dependencies.jar) into your project dependency list first.

**Comment by arvind4141** [comment]
@pgadient I've managed to solve the issue, thank you so much for the help - I really appreciate it!
